version: '3.8'
services:
  padq-business-investscene.db:
    image: mysql:5.7
    environment:
      MYSQL_DATABASE: finance_all
      MYSQL_ROOT_PASSWORD: 123456
    command:
      --character-set-server=utf8mb4
      --collation-server=utf8mb4_general_ci
      --default-authentication-plugin=mysql_native_password
      --explicit_defaults_for_timestamp=true
      --lower_case_table_names=1
      --max_allowed_packet=200M;
    ports:
      - 3307:3306
    volumes:
      - ./mysql/init:/docker-entrypoint-initdb.d
      - ./mysql/sql:/sql
      - ./mysql/data:/var/lib/mysql
      # - ./Services/Business/InvestmentScenGeneration/mysql/initdb:/docker-entrypoint-initdb.d
      # - ./Services/Business/InvestmentScenGeneration/mysql/sql:/sql
      # - ./Services/Business/InvestmentScenGeneration/mysql/data:/var/lib/mysql

      # - mysql_data:/var/lib/mysql
      # - "./mysql/config:/etc/mysql/conf.d"
      # - ./Services/Business/InvestmentScenGeneration/mysql/data:/var/lib/mysql
      # - "./Services/Business/InvestmentScenGeneration/mysql/config:/etc/mysql/conf.d"
      # - ./Services/Business/InvestmentScenGeneration/mysql/initdb/finance_all.sql:/docker-entrypoint-initdb.d/finance_all.sql
  padq-business-investscene.backend:
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://padq-business-investscene.db:3306/finance_all?useUnicode=true&characterEncoding=utf8&timeZone=GMT%2B8&useSSL=false
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: 123456
      SPRING_DATASOURCE_DRIVER_CLASS_NAME: com.mysql.cj.jdbc.Driver


      
  padq-business-investscene.flask:
    ports:
      - "5000:5000"   

# sjj 部分
  padq-business-investscene.sjj-mongodb:
    volumes:
      - ./Services/Business/InvestmentScenGeneration/stock-backend-raw-main/db:/data/db

  padq-business-investscene.sjj-backend:
    volumes:
      - ./Services/Business/InvestmentScenGeneration/stock-backend-raw-main/python-src/:/usr/src/stock-backend/python-src/
      - ./Services/Business/InvestmentScenGeneration/stock-backend-raw-main/algorithm/:/usr/src/stock-backend/algorithm/
      - ./Services/Business/InvestmentScenGeneration/stock-backend-raw-main/cron-algorithm/:/usr/src/stock-backend/cron-algorithm/
      - ./Services/Business/InvestmentScenGeneration/stock-backend-raw-main/Config.toml:/usr/src/stock-backend/Config.toml
    environment:
      - CONN=mongodb://padq-business-investscene.sjj-mongodb:27017
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "5"
  
  padq-business-investscene.sjj-notebook:
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "5"
    ports:
      - 9000:8888
    volumes:
      - ./Services/Business/InvestmentScenGeneration/stock-backend-raw-main/:/home/jovyan/work/
      - ./Services/Business/InvestmentScenGeneration/stock-backend-raw-main/configure_environment.sh:/usr/local/bin/before-notebook.d/configure_environment.sh
    environment:
      - JUPYTER_TOKEN=1233ccdb3d1f642dca21b7ed2646df01224d15670aeea220 

  padq-business-investscene.nginx:
    ports:
      - 80:9528
      - 81:80
    volumes:
      - ./Services/Business/InvestmentScenGeneration/finance-integration/nginx/finance-integration.conf:/etc/nginx/conf.d/default.conf
      - ./Services/Business/InvestmentScenGeneration/finance-integration/dist/:/usr/share/nginx/html/
      - ./Services/Business/InvestmentScenGeneration/stock-backend-raw-main/www/:/usr/share/nginx/sjj/ 